apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: myapp-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:590183945701:certificate/04e3d5bb-f4bb-41fb-848f-25dfab789579
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/actions.ssl-redirect: >
      {"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","StatusCode":"HTTP_301"}}
    argocd.argoproj.io/tracking-id: default:networking.k8s.io/Ingress:default/myapp-ingress
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp
                port:
                  number: 8000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: default:/Secret:default/prometheus-sa-token
    kubernetes.io/service-account.name: prometheus-sa
  name: prometheus-sa-token
  namespace: default
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
    verbs: ["get"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-k8s-role-binding
roleRef:
  kind: ClusterRole
  name: prometheus-k8s-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
    namespace: default

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    argocd.argoproj.io/tracking-id: default:/ConfigMap:default/my-config
data:
  # Database configuration
  MYSQL_DATABASE: "myapp_db"
  DB_HOST: "mydb.default.svc.cluster.local"
  DB_NAME: "myapp_db"
  
  # SQL initialization script
  init.sql: |
    CREATE DATABASE IF NOT EXISTS myapp_db;
    USE myapp_db;
    
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    INSERT INTO users (name, email) VALUES 
    ('John Doe', 'john@example.com'),
    ('Jane Smith', 'jane@example.com')
    ON DUPLICATE KEY UPDATE name=VALUES(name);

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - appservice.yml
  - configmap.yml
  - dbservice.yml
  - dbstatefullset.yml
  - secret.yml
  - appdeployment.yml
  - ingress.yml
  - prometheus-access.yml
  - storageclass.yml
  - svc_monitoring.yml
