apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - appservice.yml
  - configmap.yml
  - dbservice.yml
  - dbstatefullset.yml
  - secret.yml
  - appdeployment.yml
  - ingress.yml
  - prometheus-access.yml
  - storageclass.yml
  - svc_monitoring.yml